---

- hosts: all
  tags: apache,httpd,update 
  become: true
  tasks:

  - name: Install Updates (Ubuntu)
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
      
  - name: Install Updates (OracleLinux)
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "OracleLinux"

  - name: Install apache and php packages (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: present #latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php packages (OracleLinux)
    tags: apache,apache2,OracleLinux
    dnf:
      name:
        - httpd
        - php
      state: present #latest
    when: ansible_distribution == "OracleLinux"

  - name: Start httpd OracleLinux
    tags: apache, centOS, OracleLinux,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"


