# This task Installs system updates for both Ubuntu and OracleLinux.
- name: Install Updates (Ubuntu)
  tags: always
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Install Updates (OracleLinux)
  tags: always
  dnf:
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "OracleLinux"

# This task Installs Apache and PHP packages for web server setup (Ubuntu and OracleLinux).
- name: Install apache and php packages (Ubuntu)
  tags: apache,apache2,php,Ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: present #latest
  when: ansible_distribution == "Ubuntu"

- name: Install apache and php packages (OracleLinux)
  tags: apache,apache2,httpd,php,OracleLinux
  dnf:
    name:
      - httpd
      - php
    state: present #latest
  when: ansible_distribution == "OracleLinux"

# This task Starts and enables the Apache service (only for OracleLinux).
- name: Start httpd OracleLinux
  tags: apache, centOS, OracleLinux,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "OracleLinux"

# This task Updates the ServerAdmin directive in the Apache configuration file for both Ubuntu and OracleLinux.
- name: Update ServerAdmin in Apache config file (Ubuntu) # Section:B, Question 2a
  tags: apache,apache2,Ubuntu
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ServerAdmin'            # Search for the line that begins with ServerAdmin
    line: 'ServerAdmin martin.mato@ingrydacademy.com'
  when: ansible_distribution == "Ubuntu"

- name: Update ServerAdmin in Apache config file (OracleLinux) # Section:B, Question 2a
  tags: apache,apache2,httpd,OracleLinux
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'            # Search for the line that begins with ServerAdmin
    line: 'ServerAdmin martin.mato@ingrydacademy.com'
  when: ansible_distribution == "OracleLinux"

# This task Restarts the Apache service (only for OracleLinux).
- name: restart apache
  tags: httpd,OracleLinux,apache,apache2
  service:
    name: httpd
    state: restarted
  when: ansible_distribution == "OracleLinux"

# This task Installs Firewalld (Ubuntu and OracleLinux).
- name: Install Firewalld (Ubuntu)
  tags: firewalld,Ubuntu
  apt:
    name: firewalld
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Firewalld (OracleLinux)
  tags: firewalld,OracleLinux
  dnf:
    name: firewalld
    state: present
  when: ansible_distribution == "OracleLinux"

# This task Opens HTTP and HTTPS ports in the firewall for both Ubuntu and OracleLinux.
- name: Open HTTP and HTTPS ports # Section:B, Question 2b
  tags: http,https,Ubuntu, OracleLinux,firewalld
  ansible.builtin.firewalld:
    service: "{{ item }}"             # Open the items HTTP and HTTPS ports in a loop
    state: enabled
    immediate: yes
    permanent: yes
  loop:
    - http
    - https

# This task Starts and enables the Firewalld service (Ubuntu and OracleLinux).
- name: Start and enable firewalld # Section:B, Question 2c
  tags: firewalld,Ubuntu,OracleLinux
  systemd:
    name: firewalld
    state: started
    enabled: yes

